AziendaSpedizioniApp/Controllers/LoginController.cs
using AziendaSpedizioniApp.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace AziendaSpedizioniApp.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Utente U)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["ConnectionStringDB"].ConnectionString;
            SqlConnection sqlConnection = new SqlConnection(connectionString);
            try
            {
                sqlConnection.Open();
                SqlCommand sqlCommand = new SqlCommand("SELECT * FROM AUTH WHERE Username=@Username And PasswordUser=@PasswordUser", sqlConnection);
                sqlCommand.Parameters.AddWithValue("Username", U.UsernameUtente);
                sqlCommand.Parameters.AddWithValue("PasswordUser", U.PasswordUtente);
                SqlDataReader reader = sqlCommand.ExecuteReader();
                if (reader.HasRows)
                {
                    FormsAuthentication.SetAuthCookie(U.UsernameUtente, false);
                    return RedirectToAction("Index", "Admin");
                }
                else
                {
                    ViewBag.AuthError = "Autenticazione non riuscita";
                    return View();
                }
            }
            catch (Exception ex)
            {

            }
            finally { sqlConnection.Close(); }
            return RedirectToAction("Index", "Home");
        }
    }
}

AziendaSpedizioniApp/Controllers/SearchSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AziendaSpedizioniApp.Controllers
{
    public class SearchSController : Controller
    {
        // GET: SearchS
        public ActionResult Index()
        {
            return View();
        }
    }
}

AziendaSpedizioniApp/Controllers/SpedizioniController.cs
using AziendaSpedizioniApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AziendaSpedizioniApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SpedizioniController : Controller
    {
       
        // GET: Spedizioni
        public ActionResult Index()
        {
            List<Spedizione> spedizioni = DB.ListaSpedizioni();
            return View(spedizioni);
        }
        public List<SelectListItem> DescrizioneMittente
        {
            get
            {
                List<Cliente> listaClienti = new List<Cliente>();
                listaClienti = DB.ListaClienti();
                List<SelectListItem> selectListItems = new List<SelectListItem>();
                foreach (Cliente c in listaClienti)
                {
                    SelectListItem select = new SelectListItem { Text = $"{c.Nome} {c.Cognome}", Value = c.Id.ToString() };
                    selectListItems.Add(select);
                }
                return selectListItems;
            }
        }
        [HttpGet]
        public ActionResult AggiornamentoSped()
        {
            List<AggiornamentoSpedizioni>aggSpedizioni = DB.ListaAggiornamenti();
            return View(aggSpedizioni);
        }
        [HttpGet]
        public ActionResult Create() 
        {
            ViewBag.listaClienti = DescrizioneMittente;
            return View();
        }
        [HttpPost]
        public ActionResult Create(Spedizione spedizione)
        {
            if (ModelState.IsValid)
            {
                DB.CreaSpedizione(spedizione);
                return RedirectToAction("Index");
            }
            else { return View(); }
        }
    }
}

AziendaSpedizioniApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Applicazione ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
  
</head>
<body>
    @{
        int widthLogoNav = 50;
    }
    @if (User.IsInRole("Admin"))
    {
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-white border-bottom">
            <div class="container">
                <img style="width:@(widthLogoNav)px;" src="~/Content/ImgProgetto/Logo_BRT.png" />
                @Html.ActionLink("Home", "Index", "Admin", new { area = "" }, new { @class = "navbar-brand" })
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Attiva/Disattiva spostamento" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li>@Html.ActionLink("Cerca Spedizione", "Index", "SearchS", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Gestione Clienti", "Create", "Clienti", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Gestione Spedizioni", "AggiornamentoSped", "Spedizioni", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Queries", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>

                        </li>
                    </ul>
                    <div class="dropdown">
                        <a href="/Admin/Index" class="d-flex align-items-center link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="~/Content/ImgProgetto/imageUser.png" alt="" width="32" height="32" class="rounded-circle me-2">
                            <strong class="text-danger">@User.Identity.Name</strong>
                        </a>
                        <ul class="dropdown-menu text-small shadow">
                            <li><a class="dropdown-item" href="/Logout/Logout">Logout</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    }
    else
    {
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-white border-bottom">
            <div class="container">
                <img class="me-2" style="width:@(widthLogoNav)px;" src="~/Content/ImgProgetto/Logo_BRT.png" />
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Attiva/Disattiva spostamento" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="link">@Html.ActionLink("Cerca Spedizione", "Index", "SearchS", new { area = "" }, new { @class = "nav-link" })</li>
                        <li class="link">@Html.ActionLink("Accesso Amministratori", "Login", "Login", new { area = "" }, new { @class = "nav-link" })</li>
                    </ul>
                </div>
            </div>
        </nav>
    }
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - BARTOLINI Express</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/bootstrap.bundle.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>